## Config file for sample.py project
title = 'PhantomTest'
sessionId = 'phantom'

minExpectedDicomSize = 100000 # double check 
scanNum = [11]


plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'Value'
plotXRangeLow = 0
plotXRangeHigh = 333
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = true


## may need change 
imgDir = '/home/rtfmri/Documents/bridge'
##dicomDir = '/Users/peetal/Desktop/example_dicom/'   
codeDir = '/home/rtfmri/Documents/rt-cloud/projects/phantom_test'  
datestr = '20211026'
refBoldScanNum = 7
strucScanNum = 6
subjectName = 'sub_test'
dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm" 
##dicomNamePattern = "0414151_strongbad01{SCAN:03d}_{TR:04d}_001"
roi = ["/home/rtfmri/Documents/rt-cloud/projects/phantom_test/data/roi/rsc_roi_big_resampled.nii.gz"]
numTR_func_run = 160  # the code will expect this number of volumes to be processed. 

## may not use
##subjectNum = 101
##subjectDay = 1
##sessionNum = 1
